site_name: Desenvolvedores - Consultar.io
site_url: https://consultar.dev
theme:
  name: material
  custom_dir: overrides
  language: pt
  palette:
    scheme: slate
    primary: black
  features:
    - content.code.copy
    - navigation.footer
    - navigation.expand
    - navigation.indexes
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
plugins:
  - search
  - redirects:
      redirect_maps:
        "cnpj.md": "endpoints/cnpj.md"
        "cpf.md": "endpoints/cpf.md"
        "inscricao-estadual.md": "endpoints/inscricao-estadual.md"
        "inscricao-municipal.md": "endpoints/inscricao-municipal.md"
        "cep.md": "endpoints/cep.md"
        "latitude-longitude.md": "endpoints/latitude-longitude.md"
        "crm.md": "endpoints/crm.md"
        "cro.md": "endpoints/cro.md"
        "crbm.md": "endpoints/crbm.md"
        "crf.md": "endpoints/crf.md"
nav:
  - Introdução: index.md
  - Ambientes: ambientes.md
  - Autenticação: autenticacao.md
  - Endpoints:
      - endpoints/index.md
      - CNPJ: endpoints/cnpj.md
      - CPF: endpoints/cpf.md
      - Inscrição Estadual: endpoints/inscricao-estadual.md
      - Inscrição Municipal: endpoints/inscricao-municipal.md
      - CEP: endpoints/cep.md
      - Latitude/Longitude: endpoints/latitude-longitude.md
      - CRM: endpoints/crm.md
      - CRO: endpoints/cro.md
      - CRBM: endpoints/crbm.md
      - CRF: endpoints/crf.md
  - Exemplos:
      - exemplos/index.md
      - Python: exemplos/python.md
  - Suporte: suporte.md
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/consultar-io/
  analytics:
    provider: custom
    property: phc_Q7stlDDd5WU2m3lf8F1oiYyd5XPf3ggtnSYT6up6VlA
    host: https://us.i.posthog.com
copyright: <span>Expanda Tecnologia da Informação LTDA.</span> <span>(CNPJ 42.515.236/0001-00)</span>
