site_name: Desenvolvedores - Consultar.io
site_url: https://consultar.dev
theme:
  name: material
  language: pt
  palette:
    scheme: slate
  features:
    - content.code.copy
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
plugins:
  - search
nav:
  - Introdução: index.md
  - Ambientes: ambientes.md
  - Autenticação: autenticacao.md
  - CNPJ: cnpj.md
  - Inscrição Estadual (Beta): inscricao-estadual.md
  - CRM: crm.md
  - CRO: cro.md
  - CRBM (Beta): crbm.md
  - CRF (Beta): crf.md
  - CEP (Beta): cep.md
  - Latitude e Longitude (Beta): latitude-longitude.md
  - Suporte: suporte.md
