site_name: Documentação Consultar.io
site_url: https://consultar.dev
theme:
  name: material
  language: pt
  palette:
    scheme: slate
  features:
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences