site_name: Documentação API Consultar.io
site_url: https://consultar.dev
theme:
  name: material
  language: pt
  palette:
    scheme: slate
  features:
    - content.code.copy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
plugins:
  - search
nav:
  - Introdução: index.md
  - Ambientes: ambientes.md
  - Autenticação: autenticacao.md
  - CNPJ: cnpj.md
  - Inscrição Estadual: inscricao-estadual.md
  - CRM: crm.md
  - CRO: cro.md
  - CRBM: crbm.md
  - CRF: crf.md
  - CEP: cep.md
  - Latitude e Longitude: latitude-longitude.md
